# Better read on VSCode with the TODO Highlight v2 module

### General information 

#  Name displayed in the top menu and in the browsers tabs
site_name: Nanoguild
#  URL of the website
site_url: https://flaghunter01.github.io/nanotest/
# GitHub repo URL
repo_url: https://github.com/FlagHunter01/nanotest/
#  GitHub repo name
repo_name: Nanoguild
# Location of the files on the repo
edit_uri: edit/main/docs

### Navigation

nav:
  - Welcome: 
    - index.md
    - Objectifs: objectifs.md
    - Outils:
      - MarkDown: https://documentation.frolov.eu/misc/md/main.html
      - GitHub: https://github.com
  - Entreprises Deeptech: aaa.md
  - Knowledge base: bbb.md
  - Nanoguild kickoff: ccc.md

### Theme customization

theme:
  # Enables the material theme
  name: material

  ## Colors

  palette:
      primary: blue
      accent: teal

  ## Font

  # If the privacy module isn't used, uncomment the following line to stay in GDPR
  #font: false
  font:
    # All text except code
    text: Roboto
    # Inline and block code
    code: Roboto Mono
  
  ## Language

  # Don't forget to change if in multilingual project
  language: en

  ## Logo and icons

  icon:
    logo: material/robot-outline
  # Favicon (icon in the browsers tab)
  favicon: assets/favicon.png

  features:
    
    ## Navigation

    # Monopage mode using XHR
    - navigation.instant
    # Prefetch the page when the user hovers the link to it
    - navigation.instant.prefetch
    # Show loading progress bar (not shown if loading takes less than 0.4s) 
    - navigation.instant.progress
    # Link preview 
    - navigation.instant.preview
    # Anchor tracking
    - navigation.tracking
    # Display tabs in top menu
    - navigation.tabs
    # Breadcrumbs on top of the page
    - navigation.path
    # Allow sections to have index pages
    - navigation.indexes
    # Back to top button
    - navigation.top
    # Footer nav
    - navigation.footer

    ## Search

    # Search autocompletion
    - search.suggest
    # Highlight hits
    - search.highlight

    ## GitHub integration
    
    # View page source
    - content.action.view

    ## Code blocks

    # Copy button
    - content.code.copy
    # Line selection button
    - content.code.select
    # Annotations
    - content.code.annotate

    ## Misc

    # Link content tabs togeather
    - content.tabs.link
    # Display footnotes as tooltips
    - content.footnote.tooltips
    # Tooltips
    - content.tooltips
    
extra:
  ### Socials

  # customize
  social:
    - icon: material/github
      link: https://github.com/FlagHunter01

markdown_extensions:
  # Abbreviations: RER *[RER]: Réseau Express Régional  --> <p><abbr title="Réseau Express Régional">RER</abbr></p>
  - abbr
  # Admonitions (or call-outs)
  - admonition
  # Collapseable admonitions
  - pymdownx.details
  # Annotations 
  - md_in_html
  # Inline footnotes
  - footnotes
  # Table of contents
  - toc:
    # Make the anchor visible
      permalink: ⚓︎
  # Tables
  - tables
  # Better bold and italic detection
  - pymdownx.betterem
  # Text highlighting
  - pymdownx.caret
  # Code hightlighting
  - pymdownx.highlight:
      anchor_linenums: true
  # Inline code highlighting
  - pymdownx.inlinehilite
  # Nesting code and admonitions
  - pymdownx.superfences
  # Subscript 
  - pymdownx.mark
  # Superscript 
  - pymdownx.tilde
  # Diff support
  - pymdownx.critic
  # Emoji
  # Render keyboard keys
  - pymdownx.keys
  # Convert strings to symbols e.g.: &copy --> ©
  - pymdownx.smartsymbols
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Lists with checkboxes
  - pymdownx.tasklist:
      custom_checkbox: true
    # Make them clickable
      clickable_checkbox: true
  # Buttons
  - attr_list
